environments:
  production:
  ci:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: ghost
  chart: bitnami/ghost
  version: 10.1.12
  values:
  - ./config/ghost-values.yaml.gotmpl
